//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top_2000_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liedje
    {
        public int Id { get; set; }
        public string Titel { get; set; }
        public string Artiest { get; set; }
        public int Jaar { get; set; }
        public int Plaats { get; set; }
        public int PlaatsVorigjaar { get; set; }
    }
}
